on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: check-changelog
      run: node ./common/scripts/install-run-rush.js change -v
    - name: install
      run: node ./common/scripts/install-run-rush.js install --no-link
    - name: link
      run: node ./common/scripts/install-run-rush.js link
    - name: build
      run: node ./common/scripts/install-run-rush.js rebuild --verbose
    - name: lint
      run: node ./common/scripts/install-run-rush.js lint
    - name: run unit tests
      run: node ./common/scripts/install-run-rush.js test:unit
    - name: upload code coverage to codecov
      uses: codecov/codecov-action@v1
    - name: run integration tests
      run: node ./common/scripts/install-run-rush.js test:integration

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install
      run: node ./common/scripts/install-run-rush.js install --no-link
    - name: link
      run: node ./common/scripts/install-run-rush.js link
    - name: build
      run: node ./common/scripts/install-run-rush.js rebuild --verbose
    - name: publish
      run: node ./common/scripts/install-run-rush.js publish -a -b master
